version: '3'
services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    # command: redis-server --requirepass howtolovelife
  redis-ui:
    image: patrikx3/p3x-redis-ui:latest
    ports:
        - 7843:7843
    volumes:
        - p3x-redis:/settings
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
      - /app/.venv
    depends_on:
      - redis
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
volumes:
  p3x-redis: